baseURL = 'https://waveismagic.github.io/'
languageCode = 'en-de'
title = 'Astrophysical Waves'
theme = 'ananke'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params]
  featured_image_class = "contain"
